// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyDQsNxpYUNaWLiAH-8KsbzuVU04r773P4U',
    // appId: '1:472955726425:android:bc058839bcfdd9c76a5f48',
    // messagingSenderId: '472955726425',
    // projectId: 'blood-donation-app-e4c67',
    // storageBucket: 'blood-donation-app-e4c67.appspot.com',
    apiKey: 'AIzaSyAnavZ6lRIn8cNGaw7WwZ2TCwhIbm5xKvk',
    appId: '1:78097618497:android:ef5db4ba1eb713b47f18c0',
    messagingSenderId: '78097618497',
    projectId: 'freelance-ecommerce',
    storageBucket: 'freelance-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUcDBLhSTPfd8FyIrolyvf77EAX_lPP4U',
    appId: '1:78097618497:ios:826a4c9f1424f4107f18c0',
    messagingSenderId: '78097618497',
    projectId: 'freelance-ecommerce',
    storageBucket: 'freelance-ecommerce.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
